***REMOVED*** IMPORTANT: This file was generated by Cucumber 0.4.2
***REMOVED*** Edit at your own peril - it's recommended to regenerate this file
***REMOVED*** in the future when you upgrade to a newer version of Cucumber.
***REMOVED*** Consider adding your own code to a new file instead of editing this one.

***REMOVED*** Sets up the Rails environment for Cucumber
ENV["RAILS_ENV"] ||= "cucumber"
require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')
require 'cucumber/rails/world'

***REMOVED*** If you set this to true, each scenario will run in a database transaction.
***REMOVED*** You can still turn off transactions on a per-scenario basis, simply tagging 
***REMOVED*** a feature or scenario with the @no-txn tag. 
***REMOVED***
***REMOVED*** If you set this to false, transactions will be off for all scenarios,
***REMOVED*** regardless of whether you use @no-txn or not.
***REMOVED***
***REMOVED*** Beware that turning transactions off will leave data in your database 
***REMOVED*** after each scenario, which can lead to hard-to-debug failures in 
***REMOVED*** subsequent scenarios. If you do this, we recommend you create a Before
***REMOVED*** block that will explicitly put your database in a known state.
Cucumber::Rails::World.use_transactional_fixtures = true

***REMOVED*** If you set this to false, any error raised from within your app will bubble 
***REMOVED*** up to your step definition and out to cucumber unless you catch it somewhere
***REMOVED*** on the way. You can make Rails rescue errors and render error pages on a
***REMOVED*** per-scenario basis by tagging a scenario or feature with the @allow-rescue tag.
***REMOVED***
***REMOVED*** If you set this to true, Rails will rescue all errors and render error
***REMOVED*** pages, more or less in the same way your application would behave in the
***REMOVED*** default production environment. It's not recommended to do this for all
***REMOVED*** of your scenarios, as this makes it hard to discover errors in your application.
ActionController::Base.allow_rescue = false

require 'cucumber'
***REMOVED*** Comment out the next line if you don't want Cucumber Unicode support
require 'cucumber/formatter/unicode'
require 'cucumber/webrat/element_locator' ***REMOVED*** Lets you do table.diff!(element_at('***REMOVED***my_table_or_dl_or_ul_or_ol').to_table)
require 'cucumber/rails/rspec'

require 'webrat'
require 'webrat/core/matchers' 
Webrat.configure do |config|
  config.mode = :rails
  config.open_error_files = false ***REMOVED*** Set to true if you want error pages to pop up in the browser
  
end

$KCODE=''
