version: 0.2

env:
  variables:
    IMAGE_NAME: octobeehive/cicd
  secrets-manager:
    PRIVKEY: BeehivePrivkey
    FULLCHAIN: BeehiveFullchain
    DOCKERRUN: BeehiveDockerrun
    DOTENV: BeehiveDotEnv
    SPENCRYPTCERT: BeehiveSpEncryptCert
    SPENCRYPTKEY: BeehiveSpEncryptKey
    SPSIGNINGCERT: BeehiveSpSigningCert
    SPSIGNINGKEY: BeehiveSpSigningKey

phases:
  build:
      #Build and Push image to OCTO Dockerhub
    commands:
      - echo $PRIVKEY > config/apache2/privkey.pem
      - echo $FULLCHAIN > config/apache2/fullchain.pem
      - echo $DOTENV > .env
      - echo $SPENCRYPTCERT > config/shibboleth/sp-encrypt-cert.pem
      - echo $SPENCRYPTKEY > config/shibboleth/sp-encrypt-key.pem
      - echo $SPSIGNINGCERT > config/shibboleth/sp-signing-cert.pem
      - echo $SPSIGNINGKEY > config/shibboleth/sp-signing-key.pem
      - docker build -t $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
      - docker push $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo $DOCKERRUN
      - echo config/apache2/fullchain.pem
      - echo $PRIVKEY
      - echo $DOTENV
      - echo $DOCKERRUN > Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json

